#! /usr/bin/env sh
# Source: https://github.com/Aloxaf/fzf-tab/wiki/Preview
# default fzf-tab preview script
# this is a example of .lessfilter, you can change it
mime=$(file -bL --mime-type "$1")
category=${mime%%/*}
kind=${mime##*/}
if [ -d "$1" ]; then
    eza --git -1 --color=always --icons "$1"
    # elif [ "$category" = image ]; then # image preview
    # chafa --format=symbols --size= "$1"
#   exiftool "$1"
#   elif [ "$kind" = vnd.openxmlformats-officedocument.spreadsheetml.sheet ] || \ # spreadsheets
#   [ "$kind" = vnd.ms-excel ]; then
#   in2csv "$1" | xsv table | bat -ltsv --color=always
elif [ "$category" = text ]; then
    bat --color=always --style=numbers --line-range=:500 "$1"
else
    lesspipe.sh "$1" | bat --color=always
fi
# lesspipe.sh don't use eza, bat and chafa, it use ls and exiftool. so we create a lessfilter.
